name: CI

on:
  push:
    branches:
      - master
      - aaaaaan-action-s
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [windows-2019, macos-latest, ubuntu-latest]
        arch: [x64]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
        env:
          npm_config_arch: ${{ matrix.arch }}
          TARGET_ARCH: ${{ matrix.arch }}
      - name: Test
        run: npm test
