name: CI

on:
  push:
    branches:
      - master
      - aaaaaan-action-s
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        # node: [16, 14, 12, 10]
        node: [16]
        os: [windows-2019, macos-latest, ubuntu-latest]
        arch: [x64]
        # include:
        #   - os: windows-2019
        #     arch: x86
        #     node: 16
        #   - os: windows-2019
        #     arch: x86
        #     node: 14
        #   - os: windows-2019
        #     arch: x86
        #     node: 12
        #   - os: windows-2019
        #     arch: x86
        #     node: 10
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure Windows env
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          npm config set msvs_version 2019
        # See https://github.com/nodejs/node-gyp/issues/1574#issuecomment-554187531
      - name: Configure macOS env
        run: |
          echo "CXXFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV
          echo "LDFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV
        if: ${{ startsWith(matrix.os, 'macos') }}
        # Needed to fix node-webkit prebuilds, see https://github.com/nwjs/node/issues/46
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        with:
          python-version: 2.7
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
        env:
          npm_config_arch: ${{ matrix.arch }}
          TARGET_ARCH: ${{ matrix.arch }}
      - name: Test
        run: npm test
        env:
          GYP_MSVS_OVERRIDE_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
          GYP_MSVS_VERSION: 2019
