name: CI

on:
  push:
    branches:
      - master
      - aaaaaan-action-s
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        node: [16, 14, 12, 10]
        os: [windows-2019, windows-2022, macos-10.15, macos-11, ubuntu-latest]
        arch: [x64]
        include:
          - os: windows-2019
            arch: x86
          - os: windows-2022
            arch: x86
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
      - name: Install
        run: npm install
        env:
          npm_config_arch: ${{ matrix.arch }}
          TARGET_ARCH: ${{ matrix.arch }}
      - name: Test
        run: npm test
